In [3]:
%load_ext autoreload
%autoreload 2
from harambot.lib import analyze
import os
import datetime

DATA_PATH = os.path.join('harambot','data','result.json')
dt = analyze.read(DATA_PATH,keep_event=False)
first_message = analyze.get_first_message(dt)
first_message.head(n=3)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

<div>
<style>
    .dataframe thead tr:only-child th {
        text-align: right;
    }

    .dataframe thead th {
        text-align: left;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>body</th>
      <th>type</th>
      <th>timestamp</th>
      <th>messageReactions</th>
    </tr>
    <tr>
      <th>senderID</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>653552684</th>
      <td>Sup boys. Horaire de la semaine.\nLundi : refu...</td>
      <td>message</td>
      <td>2016-08-28 16:21:09.566</td>
      <td>[]</td>
    </tr>
    <tr>
      <th>1522853517</th>
      <td>üëå</td>
      <td>message</td>
      <td>2016-08-28 16:21:52.144</td>
      <td>[]</td>
    </tr>
    <tr>
      <th>100000516111803</th>
      <td>üí™üèº</td>
      <td>message</td>
      <td>2016-08-28 16:21:54.712</td>
      <td>[]</td>
    </tr>
  </tbody>
</table>
</div>

In [4]:
# Find message with reactions
dt['msgWith'] = dt['messageReactions'].apply(lambda k: any(k))
# Get the number of reactions
dt['messageReactions'] = dt['messageReactions'].apply(lambda k: len(k))

reac_per_sender = dt.groupby('senderID')['messageReactions']

dt = (dt.groupby('senderID')['msgWith'].sum() / reac_per_sender.count()).reset_index()
dt = dt.merge(reac_per_sender.mean().reset_index(), on='senderID')

# Rename columns
dt.columns = ['senderID', 'msg with emote', 'emote per msg']

In [5]:
dt.sort_values('msg with emote')

<div>
<style>
    .dataframe thead tr:only-child th {
        text-align: right;
    }

    .dataframe thead th {
        text-align: left;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>senderID</th>
      <th>msg with emote</th>
      <th>emote per msg</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>1</th>
      <td>100000516111803</td>
      <td>0.077441</td>
      <td>0.135802</td>
    </tr>
    <tr>
      <th>3</th>
      <td>100002126340389</td>
      <td>0.097778</td>
      <td>0.120000</td>
    </tr>
    <tr>
      <th>6</th>
      <td>100003881954612</td>
      <td>0.101671</td>
      <td>0.139276</td>
    </tr>
    <tr>
      <th>8</th>
      <td>1069227265</td>
      <td>0.150905</td>
      <td>0.212816</td>
    </tr>
    <tr>
      <th>16</th>
      <td>667477606</td>
      <td>0.167122</td>
      <td>0.263402</td>
    </tr>
    <tr>
      <th>12</th>
      <td>1522853517</td>
      <td>0.169471</td>
      <td>0.251855</td>
    </tr>
    <tr>
      <th>15</th>
      <td>653552684</td>
      <td>0.169979</td>
      <td>0.248201</td>
    </tr>
    <tr>
      <th>13</th>
      <td>548698913</td>
      <td>0.187793</td>
      <td>0.366197</td>
    </tr>
    <tr>
      <th>9</th>
      <td>1159543145</td>
      <td>0.192286</td>
      <td>0.282057</td>
    </tr>
    <tr>
      <th>11</th>
      <td>1363207210</td>
      <td>0.230014</td>
      <td>0.361851</td>
    </tr>
    <tr>
      <th>5</th>
      <td>100002662762932</td>
      <td>0.236174</td>
      <td>0.371332</td>
    </tr>
    <tr>
      <th>18</th>
      <td>737339817</td>
      <td>0.240132</td>
      <td>0.398843</td>
    </tr>
    <tr>
      <th>0</th>
      <td>100000221438807</td>
      <td>0.266667</td>
      <td>0.428986</td>
    </tr>
    <tr>
      <th>17</th>
      <td>720044298</td>
      <td>0.297347</td>
      <td>0.468681</td>
    </tr>
    <tr>
      <th>10</th>
      <td>1222137008</td>
      <td>0.307190</td>
      <td>0.542484</td>
    </tr>
    <tr>
      <th>4</th>
      <td>100002173328719</td>
      <td>0.312974</td>
      <td>0.518056</td>
    </tr>
    <tr>
      <th>14</th>
      <td>571194054</td>
      <td>0.316667</td>
      <td>0.616667</td>
    </tr>
    <tr>
      <th>2</th>
      <td>100000991849716</td>
      <td>0.325000</td>
      <td>0.683333</td>
    </tr>
    <tr>
      <th>7</th>
      <td>1043892580</td>
      <td>0.360465</td>
      <td>0.786822</td>
    </tr>
  </tbody>
</table>
</div>